version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=restAPI_starter_db
    ports:
      - "5432:5432"
    volumes:
      - ../src/app/data/pg:/var/lib/postgresql/data
    networks:
      - app
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    volumes:
      - ../src/app/data/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - app
    depends_on:
      - db
    restart: always

  app:
    container_name: dj_container
    build:
      context: ../src/app
      target: dev
    restart: always
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ../src/app:/app
      # show code changes locally 👉 only in development
      - ../src/app/static:/vol/app/static
    environment:
      - DEBUG=TRUE
      - DB_HOST=db
      - DB_NAME=restAPI_starter_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SECRET_KEY=cHaNgEtHiS
      - ALLOWED_HOSTS=127.0.0.1,localhost,0.0.0.0
    networks:
      - app
    depends_on:
      - db
      - pgadmin

networks:
  app:
    driver: bridge